"""empty message

Revision ID: 5b7d34679ce8
Revises: 
Create Date: 2025-06-03 16:00:21.913331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b7d34679ce8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filepath', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('OUTLINE', 'READING', 'BOOK', 'SLIDES', name='documenttype'), nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('s_season', sa.Enum('SPRING', 'SUMMER', 'FALL', name='semesterseason'), nullable=True),
    sa.Column('s_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pairdocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('q_filepath', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('a_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('a_filepath', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('OUTLINE', 'READING', 'BOOK', 'SLIDES', name='documenttype'), nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('s_season', sa.Enum('SPRING', 'SUMMER', 'FALL', name='semesterseason'), nullable=False),
    sa.Column('s_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pairdocument')
    op.drop_table('document')
    op.drop_table('course')
    # ### end Alembic commands ###
